// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4P66N9Js5WbmpdbL8t6aA-gcNWcznlc',
    appId: '1:175810142290:web:27ac674d1dbf62fa2b7f8b',
    messagingSenderId: '175810142290',
    projectId: 'evently-31eca',
    authDomain: 'evently-31eca.firebaseapp.com',
    storageBucket: 'evently-31eca.firebasestorage.app',
    measurementId: 'G-91LEW3FR4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-NLfqDFWlh1YOml6C7NOQJtSvFcXnBs',
    appId: '1:175810142290:android:e0b25c9470638caa2b7f8b',
    messagingSenderId: '175810142290',
    projectId: 'evently-31eca',
    storageBucket: 'evently-31eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzEitBi56CVjR3E5EdD3UTTKBGkg05mo',
    appId: '1:175810142290:ios:f5b8572197d9a3a62b7f8b',
    messagingSenderId: '175810142290',
    projectId: 'evently-31eca',
    storageBucket: 'evently-31eca.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpzEitBi56CVjR3E5EdD3UTTKBGkg05mo',
    appId: '1:175810142290:ios:f5b8572197d9a3a62b7f8b',
    messagingSenderId: '175810142290',
    projectId: 'evently-31eca',
    storageBucket: 'evently-31eca.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4P66N9Js5WbmpdbL8t6aA-gcNWcznlc',
    appId: '1:175810142290:web:0574fb5ff8b37d162b7f8b',
    messagingSenderId: '175810142290',
    projectId: 'evently-31eca',
    authDomain: 'evently-31eca.firebaseapp.com',
    storageBucket: 'evently-31eca.firebasestorage.app',
    measurementId: 'G-R4HXFMH1MM',
  );
}
